### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by abeyaworld** [abeyaworld/protospace-38648#4]
# URL
https://protospace-38648.onrender.com

# 備考
個人的にブランチ・コミットを分ける練習に活用してしまい、commit状況の名称が「first commit」に統一されておりません。申し訳ございません。

**Comment by shodai-ito** [comment]
@abeyaworld さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by abeyaworld** [comment]
ご確認いただきありがとうございました！引き続きよろしくお願いいたします。
